name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        make download_packer
        make build_packer_image
        make build
